### ISSUE TITLE
Update mirror automatically after a pull request is merged to main

### ISSUE THREAD

**Issue by christianguenter2** [abap2UI5/abap2UI5-mirror-renamed#1]
Now that we have the [mirror](https://github.com/abap2UI5/abap2UI5-mirror), it would be nice to automatically mirroring after a pr is merged. I think that's something which should be possible with gh actions somehow. Unfortunately that's something way over my head.

**Comment by oblomov-dev** [comment]
made a small adjustment to the permissions and now the action runs without mistakes:
https://github.com/abap2UI5/abap2UI5-mirror-renamed/actions/workflows/cron.yml

And PRs are created and can be merged with namespace /2U5/TEST:
https://github.com/abap2UI5/abap2UI5-mirror-renamed/pull/5

added some infos to the readme, i think this is a good sample repository now for everyone who wants to have a renamed version of abap2UI5.

close this issue, thank you @christianguenter2 @larshp
